spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb:
      core.MongoTemplate: debug

